import type { Metadata } from "next";
import Link from "next/link";
import FaqSchema, { type FaqItem } from "@/components/FaqSchema";

const FAQS: FaqItem[] = [
  { q: "How does Aleq automate financial reporting?", a: "Aleq is an AI accounting platform that assembles the income statement, balance sheet, and cash flow statement straight off the live trial balance of its native double-entry ledger — no exports, no pivot tables, no version-and-a-final. It drafts the month-over-month flux commentary the way a controller would, with every driver cited to the ledger, and every figure on every report drills to the journal entries, source documents, and policy behind it. Once it has learned your board package format, the pack is built and waiting the morning after close. Unlike exporting from QuickBooks or NetSuite into slides that drift, the statements are a view of the books and always tie out. Connects read-only; live in 48 hours." },
  { q: "What is flux analysis in accounting?", a: "Flux analysis — also called variance analysis — is comparing account balances across periods and explaining the meaningful changes: what moved, by how much, and why. It's the judgment-heavy last mile of the month-end close, and usually the part still written by hand the night before the board meeting. Aleq drafts it automatically: opex up $214,000 versus April, of which $180,000 is the annual D&O insurance premium booked in May and amortized over twelve months, plus two engineering hires — each driver cited to the underlying entries. You review and adjust the wording; you don't start from a blank page." },
  { q: "What should be in a monthly board reporting package?", a: "At minimum: the three financial statements — income statement, balance sheet, and cash flow — plus variance commentary explaining what moved versus the prior period and why, and the operating cuts your board expects, such as a department P&L roll-up. What separates a good pack is traceability: when a board member asks why opex jumped, the answer should be evidence, not a follow-up email. Aleq assembles the pack off the live ledger the morning after close, writes the flux commentary with drivers cited, and makes every number drillable to the journal entry behind it — so the question gets answered in the meeting." },
  { q: "What are the three main financial statements?", a: "The income statement shows revenue, costs, and profit or loss over a period; the balance sheet shows assets, liabilities, and equity at a point in time and must balance; and the cash flow statement reconciles profit to actual cash movement, typically via the indirect method. All three derive from the same trial balance and must tie together. Aleq assembles all three directly off its live ledger — when the books move, the statements move with them, every figure still ties to the penny, and any line opens to the entries behind it." },
  { q: "How do companies automate board reporting?", a: "The default is manual: close the books, export to Excel, rebuild the pivot tables, write the commentary, format the slides — a week of work after the close is technically done. Close tools like FloQast and ERPs like Sage Intacct add variance features, but the deck is still assembled by hand. Aleq automates the whole output: statements assemble off the live ledger as the month seals, flux commentary is drafted with drivers cited, and once the format is proven over a couple of cycles, the recurring pack builds itself and waits for review. New cuts, like a one-off investor request, are drafted and stop for sign-off." },
  { q: "How can we get financial reports out faster after month-end close?", a: "The lag usually isn't the close itself — it's the re-assembly afterward: exporting the trial balance, rebuilding spreadsheets, writing commentary, formatting the deck. Every export creates a copy that drifts from the books and has to be re-tied. The fix is removing the export step entirely. In Aleq, the statements are a live view of the ledger, so reporting is the close's output rather than a separate project: as the month seals, the statements and the board pack assemble in step, the flux commentary is drafted from the entries, and the pack is ready the morning after close instead of a week later." },
  { q: "Can AI write variance analysis commentary?", a: "Yes — and the useful kind cites its sources. Aleq drafts the month-over-month flux the way your controller would: revenue up 9.4% on two enterprise go-lives, gross margin up 1.2 points on an infrastructure renegotiation, opex up $214,000 on a D&O premium and two hires — each driver linked to the journal entries, bills, and policies behind it. Because the commentary is generated from the ledger rather than summarized from a spreadsheet, every claim in it is checkable with a click. You edit tone and emphasis; the assembly and the arithmetic are already done." },
  { q: "Can I trust financial reports generated by AI?", a: "Trust the traceability, not the generator. Aleq's reports aren't a model's summary of your finances — they're views of a native double-entry ledger, so the statements always tie to the trial balance by construction. Every figure drills to the journal entries, source documents, and policy behind it; every entry is logged and reversible; and drafted commentary cites its drivers to the ledger. That makes an AI-assembled report more verifiable than the typical spreadsheet export, where numbers get pasted, adjusted in the deck, and can't be traced by the time the board asks. If you can click from the number to the evidence, trust stops being a leap." },
  { q: "Will automated reporting match our existing board deck format?", a: "Aleq learns your format rather than imposing one. The reports you send every month in the same shape — the board pack, the department P&L roll-up — it assembles on its own once the format is proven over a couple of cycles, waiting the morning after close. A new schedule or a one-off investor cut is a judgment call, so it's drafted and held for your sign-off before anything goes out. That's the same supervision model as the rest of the platform: Manual, Assist, or Auto per report, with autonomy earned by repetition, not assumed." },
  { q: "Why don't my financial reports match my general ledger?", a: "The usual culprits: the report was built from an export that's now stale, late entries posted after the spreadsheet was made, adjustments typed into the deck but never journaled, or GL accounts mapped to the wrong report lines. Every copy of the books is a chance to drift. Aleq eliminates the copies: the income statement, balance sheet, and cash flow are live views of the trial balance, so when the ledger moves the statements move with it, and every figure ties to the penny by construction. If a number looks wrong, you drill to the entries behind it instead of auditing a spreadsheet." },
];

export const metadata: Metadata = {
  title: "Financial reporting — board-ready the day you close",
  description:
    "Aleq assembles your income statement, balance sheet, and cash flow off the live ledger, writes the flux commentary, and drills every number to the entry — so the board pack is ready the day you close, not a week of slides later.",
};

export default function Page() {
  return (
    <>
      <section className="pp-wrap">
        <div className="pp-hero">
          <div className="pp-hero-copy">
            <div className="pp-eyebrow">Financial reporting</div>
            <h1>Board-ready the day you close.</h1>
            <p className="pp-hero-lead">The statements assemble themselves off your live ledger — with the variance written and every number drillable to the entry behind it.</p>
            <div className="pp-actions">
              <Link className="btn btn-primary btn-lg" href="/demo">See it on your books</Link>
              <a className="btn btn-lg" href="#how">How it works</a>
            </div>
          </div>

          <div className="pp-hero-art pp-frame reveal">
            <div className="pp-card">
              <div className="pp-card-head">
                <svg className="pp-card-mark" viewBox="0 0 48 48"><use href="#aleq-mark" /></svg>
                Income statement · Sirius Robotics · May 2026
                <span className="pp-live" style={{ color: "var(--fg-muted)" }}>live</span>
              </div>
              <div className="pp-tb">
                <div className="pp-tb-row"><span className="pp-tb-acct">Revenue</span><span className="pp-num">$1,284,900</span></div>
                <div className="pp-tb-row"><span className="pp-tb-acct">Cost of revenue</span><span className="pp-num neg">$(372,100)</span></div>
                <div className="pp-tb-row"><span className="pp-tb-acct"><small>71%</small>Gross profit</span><span className="pp-num">$912,800</span></div>
                <div className="pp-tb-row"><span className="pp-tb-acct">Operating expenses</span><span className="pp-num neg">$(1,140,300)</span></div>
              </div>
              <div className="pp-tb-foot">
                <span className="pp-tb-k">Operating loss · tied to the trial balance</span>
                <span className="pp-num" style={{ fontSize: "16px", fontWeight: 600 }}>$(227,500)</span>
              </div>
            </div>
            <div className="pp-float">
              <div className="pp-float-k">right now</div>
              <div className="pp-float-v">Board pack assembled <span className="pp-ok">ready to send</span></div>
            </div>
          </div>
        </div>
      </section>

      <section className="pp-section alt" id="how">
        <div className="pp-wrap">
          <div className="pp-point">
            <div className="pp-point-copy">
              <div className="pp-eyebrow">Off the ledger, not off a spreadsheet</div>
              <h2 className="pp-h">Three statements, built from the books.</h2>
              <p className="pp-sub">The income statement, balance sheet, and cash flow assemble straight off your live trial balance — no exporting, no pivot tables, no a-version-and-a-final. When the ledger moves, the statements move with it, and every figure still ties out to the penny.</p>
            </div>
            <div className="pp-point-art reveal">
              <div className="pp-card">
                <div className="pp-card-head"><svg className="pp-card-mark" viewBox="0 0 48 48"><use href="#aleq-mark" /></svg> Statements · May 2026</div>
                <div className="pp-checks">
                  <div className="pp-checkrow"><span className="pp-learned-rule">Income statement<small>revenue through net loss</small></span><span className="pp-conf">tied out</span></div>
                  <div className="pp-checkrow"><span className="pp-learned-rule">Balance sheet<small>assets = liabilities + equity</small></span><span className="pp-conf">balanced</span></div>
                  <div className="pp-checkrow"><span className="pp-learned-rule">Cash flow<small>indirect method, off the TB</small></span><span className="pp-conf">tied out</span></div>
                </div>
                <div className="pp-tb-foot">
                  <span className="pp-tb-k">3 statements · 1 source of truth</span>
                  <span className="pp-ok">Every line drillable</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="pp-section">
        <div className="pp-wrap">
          <div className="pp-point flip">
            <div className="pp-point-copy">
              <div className="pp-eyebrow">Click any number</div>
              <h2 className="pp-h">Every figure drills to the entry.</h2>
              <p className="pp-sub">A board member asks why opex jumped. You don&apos;t go spelunking — every number on the report opens to the journal entries, the source documents, and the policy behind it. The answer is one click deep, with the evidence already attached.</p>
            </div>
            <div className="pp-point-art reveal">
              <div className="pp-card">
                <div className="pp-card-head"><svg className="pp-card-mark" viewBox="0 0 48 48"><use href="#aleq-mark" /></svg> Operating expenses · drill-down</div>
                <div className="pp-belief">
                  <div className="pp-belief-rule">Opex $1,140,300 — up $214,000 vs April</div>
                  <div className="pp-belief-meta">opens to 38 entries across 6 accounts</div>
                  <div className="pp-why"><b>What moved</b><p>$180k of the increase is annual D&amp;O insurance booked in May and amortized over 12 months; the rest is two new engineering hires. Each piece links to the bill, the policy, and the journal entry.</p></div>
                  <span className="pp-act" role="button" tabIndex={0}>Open the entries</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="pp-section alt">
        <div className="pp-wrap">
          <div className="pp-point">
            <div className="pp-point-copy">
              <div className="pp-eyebrow">Written, not just charted</div>
              <h2 className="pp-h">The flux commentary, drafted.</h2>
              <p className="pp-sub">Aleq writes the month-over-month variance analysis the way your controller would — what changed, by how much, and why — in plain language with the drivers cited. You review and adjust the wording; you don&apos;t assemble it from scratch the night before the board meeting.</p>
            </div>
            <div className="pp-point-art reveal">
              <div className="pp-card">
                <div className="pp-card-head"><svg className="pp-card-mark" viewBox="0 0 48 48"><use href="#aleq-mark" /></svg> Flux · May vs April 2026</div>
                <div className="pp-checks">
                  <div className="pp-checkrow"><span className="pp-learned-rule">Revenue +9.4%<small>two enterprise go-lives</small></span><span className="pp-conf">+$110k</span></div>
                  <div className="pp-checkrow"><span className="pp-learned-rule">Gross margin +1.2pts<small>infra renegotiation</small></span><span className="pp-conf">71%</span></div>
                  <div className="pp-checkrow"><span className="pp-learned-rule">Opex +23%<small>D&amp;O premium · 2 hires</small></span><span className="pp-conf warn">+$214k</span></div>
                </div>
                <div className="pp-tb-foot">
                  <span className="pp-tb-k">Commentary drafted · cited to the ledger</span>
                  <span className="pp-ok">ready to review</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="pp-section">
        <div className="pp-wrap">
          <div className="pp-point flip">
            <div className="pp-point-copy">
              <div className="pp-eyebrow">It earns the routine</div>
              <h2 className="pp-h">It learns your board package.</h2>
              <p className="pp-sub">The reports you send every month, in the same shape, Aleq assembles on its own once the format is proven — the deck is built and waiting the morning after close. A new schedule or a one-off investor cut is a judgment call, so it drafts and stops for your sign-off.</p>
            </div>
            <div className="pp-point-art reveal">
              <div className="pp-card">
                <div className="pp-card-head"><svg className="pp-card-mark" viewBox="0 0 48 48"><use href="#aleq-mark" /></svg> What Aleq runs, by report</div>
                <div className="pp-app-body" style={{ padding: "6px 18px 14px" }}>
                  <div className="pp-learned-row"><span className="pp-learned-rule">Monthly board pack<small>assembled 11× · same format</small></span><span className="pp-learned-bar"><i style={{ width: "100%" }} /></span><span className="pp-tag auto">Runs alone</span></div>
                  <div className="pp-learned-row"><span className="pp-learned-rule">Department P&amp;L roll-up<small>assembled 9×</small></span><span className="pp-learned-bar"><i style={{ width: "98%" }} /></span><span className="pp-tag auto">Runs alone</span></div>
                  <div className="pp-learned-row"><span className="pp-learned-rule">Investor data room cut<small>new format</small></span><span className="pp-learned-bar mid"><i style={{ width: "30%" }} /></span><span className="pp-tag asks">Asks first</span></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="pp-section alt">
        <div className="pp-narrow" style={{ textAlign: "center", marginBottom: "34px" }}>
          <div className="pp-eyebrow" style={{ display: "inline-block" }}>FAQ</div>
          <h2 className="pp-h">What finance leads ask first.</h2>
        </div>
        <div className="pp-faq reveal">
          {FAQS.map((f, i) => (
            <details key={i} open={i === 0}><summary>{f.q}</summary><p>{f.a}</p></details>
          ))}
        </div>
        <FaqSchema items={FAQS} />
      </section>

      <section className="pp-cta">
        <div className="pp-narrow">
          <h2>Send the board pack the day you close.</h2>
          <p>Connect read-only and watch Aleq assemble your statements, write the flux, and tie every number to the entry behind it — the report ready the morning after close.</p>
          <div className="pp-actions">
            <Link className="btn btn-primary btn-lg" href="/demo">See it on your books</Link>
            <Link className="btn btn-lg" href="/work">See all the work</Link>
          </div>
        </div>
      </section>
    </>
  );
}
